### ISSUE TITLE
Error making request: AxiosError: Request failed with status code 404

### ISSUE THREAD

**Issue by avaxtasulta** [croissanteth/chatgpt-token#1]
Hey thanks for this code!

I keep getting this error:
Error making request: AxiosError: Request failed with status code 404
    at settle (/media/coding/chatgpt-token/node_modules/axios/lib/core/settle.js:19:12)
    at BrotliDecompress.handleStreamEnd (/media/coding/chatgpt-token/node_modules/axios/lib/adapters/http.js:572:11)
    at BrotliDecompress.emit (node:events:529:35)
    at BrotliDecompress.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST'

I have my api key etc all set up in .env and it looks like the headers are being passed correctly.
any ideas?

**Comment by avaxtasulta** [comment]
Solved. I hadn't set up gpt-4 API access :D
